spring.application.name=star-recommender

spring.datasource.url= jdbc:postgresql://localhost:5432/star-recommender
spring.datasource.username= recommender_user
spring.datasource.password= Str0ngP@ssw0rd!2024

spring.liquibase.enabled=false
spring.jpa.hibernate.ddl-auto= update

application.transaction-db.url=jdbc:h2:file:./db/transaction
application.recommendation-db.url=jdbc:h2:file:./db/recommendation
server.port = 8080

spring.cache.type=simple
spring.cache.cache-names=userOfCache, activeUserOfCache, transactionSumCompareCache, transactionSumCompareDepositWithdrawCache
spring.cache.caffeine.spec=expireAfterWrite=10m,maximumSize=1000

spring.info.build.enabled=true
telegram.bot.token= 7944345765:AAFMf0CvArGXo_km152IEuuaGAHhN4J3-OI