spring.application.name=star-recommender

spring.datasource.url= jdbc:postgresql://localhost:5432/star-recommender
spring.datasource.username= recommender_user
spring.datasource.password= Str0ngP@ssw0rd!2024

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.jpa.hibernate.ddl-auto= update

application.transaction-db.url=jdbc:h2:file:./db/transaction
application.recommendation-db.url=jdbc:h2:file:./db/recommendation
server.port = 8080

